"use client"

import { useState } from "react"
import Image from "next/image"
import { BookOpen, Calculator, Atom, Languages, Laptop, ClipboardCheck, X } from "lucide-react"

const projects = [
  { title: "Inclusive Learner Support", description: "Individualized one-to-one and small-group interventions for learners with autism, ADHD, hearing impairment, and learning differences. Includes progress monitoring, accessible resources, and learner-centred support.", icon: BookOpen, tags: ["SNE", "IEPs", "Learner Support"] },
  { title: "Maths & Physics Tutoring", description: "Structured tutoring for primary, secondary, IGCSE, and CBE learners, using practical examples, inquiry, and differentiated instruction to build understanding and confidence.", icon: Calculator, tags: ["Mathematics", "Physics", "Tutoring"] },
  { title: "KSL Communication Support", description: "Kenyan Sign Language interpretation and communication support that helps learners with hearing impairments participate fully in education and community spaces.", icon: Languages, tags: ["KSL", "Accessibility", "Inclusion"] },
  { title: "Adaptive Classroom Practice", description: "Curriculum adaptation, assistive technology, accessible assessments, and positive behaviour support designed around individual learner profiles and measurable goals.", icon: Laptop, tags: ["Assistive Tech", "Safeguarding", "IEPs"] },
  { title: "Mathematics & Physics Practicum", description: "Competency-based Mathematics and Physics lessons using practical experiments, inquiry-based learning, schemes of work, assessments, and targeted remedial support.", icon: Atom, tags: ["CBC", "Experiments", "Assessment"] },
  { title: "Learner Progress Monitoring", description: "Continuous assessment and accurate intervention records that help teachers, parents, and multidisciplinary teams make informed support decisions.", icon: ClipboardCheck, tags: ["Assessment", "Records", "Collaboration"] },
]

export function ProjectsContent() { const [selectedProject, setSelectedProject] = useState<typeof projects[0] | null>(null); return <><div className="flex flex-col gap-6"><div><h2 className="text-2xl font-bold text-gray-900">Teaching Practice &amp; Projects</h2><p className="text-sm text-gray-500 mt-1">Click any area to explore Brian&apos;s work in inclusive education, tutoring, and learner support.</p></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-4">{projects.map((project) => { const Icon = project.icon; return <button key={project.title} onClick={() => setSelectedProject(project)} className="group p-4 bg-white rounded-xl border border-gray-200 hover:border-primary hover:shadow-lg transition-all text-left cursor-pointer"><div className="flex items-start gap-3"><div className="size-11 flex-shrink-0 flex items-center justify-center rounded-xl bg-gradient-to-br from-[#102a72] to-[#3f8f61] shadow-md"><Icon className="size-5 text-white" strokeWidth={1.8} /></div><div className="flex-1 min-w-0"><h3 className="font-bold text-gray-900 text-sm group-hover:text-primary transition-colors">{project.title}</h3><p className="text-xs text-gray-600 mt-1 leading-relaxed">{project.description}</p><div className="flex flex-wrap gap-1.5 mt-2">{project.tags.map((tag) => <span key={tag} className="px-2 py-0.5 bg-gray-100 text-gray-700 rounded-md text-[10px] font-medium">{tag}</span>)}</div></div></div></button> })}</div></div>{selectedProject && <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4"><div className="bg-white rounded-2xl max-w-2xl w-full shadow-xl"><div className="px-6 py-4 flex items-start justify-between border-b bg-blue-50"><div><h2 className="text-2xl font-bold text-gray-900">{selectedProject.title}</h2><div className="flex flex-wrap gap-2 mt-2">{selectedProject.tags.map((tag) => <span key={tag} className="px-3 py-1 bg-yellow-100 text-yellow-900 rounded-full text-xs font-semibold">{tag}</span>)}</div></div><button onClick={() => setSelectedProject(null)} className="p-2 hover:bg-gray-200 rounded-lg" aria-label="Close project details"><X className="size-5 text-gray-600" /></button></div><div className="p-6 flex flex-col gap-4"><Image src="/brian-tutoring-flyer.jpeg" alt="Brian Peru tutoring flyer" width={900} height={1200} className="w-full max-h-80 object-contain rounded-lg bg-gray-100" /><p className="text-gray-700 leading-relaxed">{selectedProject.description}</p><p className="text-sm text-gray-500">Brian Peru combines inclusive education, learner support, Mathematics and Physics tutoring, and KSL communication support.</p></div></div></div>}</> }
